# Generated by Django 5.2.6 on 2025-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('planta', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
    ]
